name: sparkflow
version: 0.0.1
author: Alexander Ewetumo
description: a flow-based approach to app development
homepage: http://github.com/influx6/sparkflow.dart
dependencies:
  ds:
    path: ../ds
  hub:
    path: ../hub
  invocable:
    path: ../invocable
  statemanager:
    path: ../statemanager
  streamable:
    path: ../streamable
