name: flow
version: 0.0.1
author: Alexander Ewetumo
email: trinoxf@gmail.com
description: a flow-based approach to app development
dependencies:
  pipes:
    path: ../pipes
  ds:
    path: ../ds
  invocable:
    path: ../invocable
  hub:
    path: ../hub
